repos:
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910
    hooks:
      - id: mypy

  - repo: https://github.com/pre-commit/mirrors-flake8
    rev: v4.0.1
    hooks:
      - id: flake8
        args: ['--max-line-length=100']  # Adjust line length as needed

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.3
    hooks:
      - id: isort

  - repo: https://github.com/pre-commit/mirrors-black
    rev: v21.12b0
    hooks:
      - id: black

  - repo: https://github.com/pre-commit/mirrors-pylint
    rev: v2.9.6
    hooks:
      - id: pylint

  - repo: https://github.com/pre-commit/mirrors-django-checkmigrations
    rev: v0.10.0
    hooks:
      - id: django-checkmigrations
